(Calendar) Add Thai DateFormat Supports
maxkeppeler/sheets-compose-dialogs pull request #54
Opened 2023-05-14 13:25 UTC by cdmochi

I wanted supports for buddhist calendar in Thai. This pull request contains localization and buddhist year supported.

2023-05-25 10:19 UTC, maxkeppeler commented
Hey, I would love to see the support for Buddhist calendar and see your PR merged!

2023-05-26 05:53 UTC, cdmochi commented
I would love to see any suggestions regarding to my PR 😀.

2023-05-26 19:28 UTC, maxkeppeler requested changes

2023-05-28 17:50 UTC, cdmochi commented on calendar/src/main/java/com/maxkeppeler/sheets/calendar/CalendarState.kt
> +
Firstly, line 214 the year in calendarView will be shown as Thai Buddhism year format if and only if Thai locale is set. 
Also, To calculate BE year manually, just add 543 to year to the BC year. You may look for more references here from the link I provided below as well. [https://wesak.org.my/calculating-b-e/#:~:text=Thus%20543%20BCE%2C%20the%20year,B%20%3D%20544%20%2B%202021%20%3D%20B.E.](url)

2023-05-28 17:52 UTC, cdmochi commented on calendar/src/main/java/com/maxkeppeler/sheets/calendar/CalendarState.kt
> +
> What does that do? Why do you have to check for locale th when clicking a year and why do you reduce the selected year amount with 543 years?

Firstly, line 214 the year in calendarView will be shown as Thai Buddhism year format if and only if Thai locale is set.

2023-05-28 17:52 UTC, cdmochi commented on calendar/src/main/java/com/maxkeppeler/sheets/calendar/CalendarState.kt
> +
> Should we consider creating a separate utility function within the utils file? I would appreciate your thoughts on this.

To calculate BE year manually, just add 543 to year to the BC year. You may look for more references here from the link I provided below as well. [https://wesak.org.my/calculating-b-e/#:~:text=Thus%20543%20BCE%2C%20the%20year,B%20%3D%20544%20%2B%202021%20%3D%20B.E.](https://github.com/maxkeppeler/sheets-compose-dialogs/pull/url)

2023-05-28 17:55 UTC, cdmochi commented on calendar/src/main/java/com/maxkeppeler/sheets/calendar/CalendarState.kt
> +
> Should we consider creating a separate utility function within the utils file? I would appreciate your thoughts on this.

I think that would make it better in this case. I'll fix it.

2023-05-29 02:56 UTC, cdmochi commented on calendar/src/main/java/com/maxkeppeler/sheets/calendar/views/YearSelectionView.kt
> +
I think so, i'll fix it

2024-10-09 14:39 UTC, maxkeppeler commented
Closed due to inactivity

2024-10-09 14:39 UTC, closed without merging